### PR TITLE
Add a content search reset when the page is reloaded

### PR DESCRIPTION
**Pull request by RichardIrala**

### CODE REVIEW

**Comment by RichardIrala** [comment]
first we need to merge this: https://github.com/0xsequence/docs/pull/203. Or I can create another branch with this PR solution. Let me know what you want

**Comment by JamesLawton** [comment]
Thanks @RichardIrala, merged the previous PR and looks good. I see that there's a merge conflict - can you fix this with an updated commit of what version to go forward with?

**Comment by RichardIrala** [comment]
sure!

**Comment by RichardIrala** [comment]
Done!

**Pull request merged**
